###################################################
# Author: Ant Bilic                               #
# Since: Feb 22, 2024                             #
# Copyright: DAFF Hitchhikers working group       #
# Version: N/A                                    #
# Maintainer: Ante Bilic                          #
# Email: ante.bilic.mr@gmail.com                  #
# Status: N/A                                     #
###################################################

"""
Processing and generating containers

This file contains code to read in conditional probability tables, and conduct
generation and processing of simulated containers.

Running: python make_containers.py -y a_input_yaml_file
or:      python make_containers.py --yaml a_input_yaml_file

"""
import argparse
from pathlib import Path
import sys
from dataclasses import dataclass, field, InitVar
from functools import lru_cache
import numpy as np
from numpy.random import Generator
import pandas as pd
from pandas.core.frame import DataFrame
from pandas.core.series import Series
from loguru import logger
from scipy.stats import beta
from tqdm import tqdm
from flatpack.src.config import Config

logger.remove()
logger.add(sys.stderr, level="INFO")
type Vector[T] = np.ndarray[tuple[int], np.dtype[T]]
type MyArrayLike[T] = list[T] | tuple[T, ...] | Vector[T] | Series | DataFrame


def get_rng() -> Generator:
    """
    Provides a BitGenerator

    Returns
    -------
    ...:  The BitGenerator

    """
    rng = np.random.default_rng()
    return rng


def rn_choice[T](aseq: MyArrayLike[T],
              probs: MyArrayLike[float],
              size: int | tuple[int] | None=None) -> np.ndarray[T]:
    """
    Generate a random sample from an a sequence

    Parameters
    ----------
    aseq : 1-D ArrayLike
        the sequence (e.g., list/array/set) of items to sample from
    probs : 1-D ArrayLike
        the associated probabilities of the items in the aseq (uniform if None)
    size : Optional[int, Tuple[int]], optional
        The output shape. The default is None (i.e., return a single item)

    Returns
    -------
    ... : array or a single item
        The generated random samples

    """
    rng: Generator = np.random.default_rng()
    return rng.choice(a=aseq, p=probs, size=size)


@lru_cache()
def no_contam_prob(base_p: float, importer_q: float, population: float=1e10) -> float:
    """
    Evaluates the threshold value x such that the probability of (non)-contamination is <= x
    with the required confidence (the latter provided as the quantile for each importer).

    Parameters
    ----------
    base_p : Tuple
        The contamination 'p_no' (or 'p_yes') value for a set of container attributes
    importer_q : float
        The quantile (from 0 to 1) for the Importer (usually randomly assigned),
        i.e., lower tail probability.
    population : int|float
        Total population size.

    Returns
    -------
    ... : float
        The Beta percentile/quantile function ("Probability Point Function"), yields a value
        that the non-contamination probability is lower or equal to, with the importer_q confidence

    """
    return beta.ppf(q=importer_q, a=base_p * population, b=(1 - base_p) * population)


@dataclass(kw_only=True)
class TheConGen:
    """
    Groups together the methods needed to generate virtual containers

    Parameters
    ----------
    cpt_top_file : Path | str
        either the top or the cpt...with...csv" files (generated by medium_risk_ext.py)
    num_containers: int
        The number of virtual containers required
    num_importers: int OR List[ Dict[str, Union[str, int, float] ]
        Either the number of importers or the List of dictionaries with 'name' (string) and 'volume'
        (int or float) keys, the values of the latter being the importers' container count or frac

    attribs : List[str]
        container attributes (usually CALSourceCountry, SCHS, RuralDest, TypeOfGoods)
    """
    cpt_top_file: InitVar[Path | str]
    num_containers: int
    num_importers: int | list[dict[str, str | int | float]]
    attribs: list[str] = field(init=False, default_factory=list)
    cpt_df: DataFrame = field(init=False, default_factory=DataFrame)

    def __post_init__(self, cpt_top_file: str | Path) -> None:
        """
        Simply to assign the cpt_df and attribs their values
        """
        if not isinstance(cpt_top_file, str | Path):
            raise TypeError("cpt_top_file must be a string or Path")
        if self.cpt_df.empty:
            self.cpt_df = pd.read_csv(cpt_top_file)
        if 'p_no' not in self.cpt_df:
            self.cpt_df['p_no'] = 1 - self.cpt_df['p_yes']
        self.attribs = self.cpt_df.columns.tolist()
        for _a in ('prop', 'p_yes', 'p_no'):
            try:
                self.attribs.remove(_a)
            except ValueError:
                logger.warning(f"\nColumn {_a} not present in the CPT table")


    def generate_containers(self) -> DataFrame:
        """
        Generate 4+ top-level attributes (i.e. CALSourceCountry, SCHS, RuralDest, TypeOfGoods)
        of containers according to  proportions ('prop') in the top CPT file.

        Raises
        ------
        ValueError
            If the sum of proportions is very much out of whack.

        Returns
        -------
        ... : DataFrame
            The table of virtual containers and their attributes

        """
        # Separate the DataFrame into the "attribs" cols table and "prop" Series:
        at_vals = self.cpt_df.loc[:, self.attribs]
        props = self.cpt_df['prop']
        total_prop = props.sum()
        if not 0.9 < total_prop < 1.1:
            raise ValueError(f"Proportions should sum to 1, but here: {total_prop}")
        # renormalise the "props" so they add up to 1:
        props = props / total_prop
        # Make random draws from the at_val raws, with relative probabilities as in the props:
        draw_containers = rn_choice(at_vals, props, self.num_containers)
        # simply return these virtual containets as a DataFrame
        return pd.DataFrame(draw_containers, columns=self.attribs)


    def importer_contamination(self, containers: DataFrame) -> None:
        """
        Assigns the 'imporrter' column values and evaluates the 'contamination'
        column values for each virtual container

        Parameters
        ----------
        containers : DataFrame
            The virtual containers with their attributes.

        Returns
        -------
        None

        """
        contam_status = ('no', 'yes')
        importer: list[int] | dict[str, int | float]
        if isinstance(self.num_importers, int):
            # A ridiculous procedure to assign labels, e.g., 0, 1, 2, ...,8 to importers
            # with the decreasing fractions, e.g., 20%, 17.8%, 15.6%, ..., 2.2%, respectively
            importer = list(range(self.num_importers))
            prs = np.linspace(start=self.num_importers, stop=1, num=len(importer))
            # renormalise these as fractions which add up to 1
            prs = prs / sum(prs)
            # assign 'importer' values to rows as a random choice based on these fractions:
            containers['importer'] = rn_choice(importer, prs, containers.shape[0])
        else:
            # Assign the 'importer' labels based on the name-volume pairs in the YAML config
            # a dict of {name: volume} values:
            importer = {dic.get(_n, ""): dic.get("volume", 0) for dic in self.num_importers
                        for _n in dic if _n == "name"}
            if all(0 <= vol <= 1 for vol in importer.values()):
                # if volumes provided as fractions, renormalise them to add up to 1
                frac_sum = sum(importer.values())
                # then turn those into whole numbers:
                importer.update({imp: round(importer.get(imp, 0) / frac_sum * self.num_containers)
                                 for imp in importer})
            try:
                containers['importer'] = [imp for imp, vol in importer.items() for _ in range(vol)]
            except ValueError as _e:
                # renormalisation off by 1 (or 2):
                logger.warning(f"\n{_e}: mismatch container count: {sum(importer.values())}")
                while containers.shape[0] > sum(importer.values()):
                    a_key = list(importer.keys())[-1]
                    importer.update({a_key: importer[a_key] + 1})
                    logger.info(f"\nIncreased container count: {sum(importer.values())}")
                while containers.shape[0] < sum(importer.values()):
                    a_key = list(importer.keys())[-1]
                    importer.update({a_key: importer[a_key] - 1})
                    logger.info(f"\nDecreased container count: {sum(importer.values())}")
                containers['importer'] = [imp for imp, vol in importer.items() for _ in range(vol)]

        # assign each importer a quantile in the 0-1 range:
        importer_quantiles: dict[int | str, float] = {imp: get_rng().random() for imp in importer}
        # Get the p_no and p_yes contamination probabilities
        # and re-index the DataFrame with the attribute column names:
        contam_probs = self.cpt_df.drop(columns='prop').set_index(self.attribs)

        contam_list = []
        # loop over all rows of the generated container attributes:
        for _i in tqdm(range(containers.shape[0])):
            # get the attribute values at the row with the index _i:
            row_i = tuple(containers.loc[_i, self.attribs])
            # get the p_no for this set of attribute values (the index of contam_probs):
            base_p_no: float = contam_probs.loc[row_i, 'p_no']
            # A base_p equal to 0 or 1 would yield an importer_ps equal to NaN. Offset it by 1e-9:
            if base_p_no == 0:
                base_p_no = 1.0e-9
            elif base_p_no == 1:
                base_p_no = 1 - 1.0e-9
            # retrieve the 'importer' value for this row:
            importer_i: str | int = containers.loc[_i, 'importer']
            # From the base_p_no, importer quantile and concentration evaluate
            # the (non)contamination probabilities using the Beta distribution:
            new_p_no = no_contam_prob(base_p_no, importer_quantiles[importer_i])
            # randomly assign the contamination status ("no"/"yes") based on these probabilities:
            assigned_contamination = rn_choice(contam_status, (new_p_no, 1 - new_p_no))
            contam_list.append(assigned_contamination)

        # add the new column 'contamination' to the DataFrame
        containers['contamination'] = contam_list


    def generate_sample_containers(self, output_file_name: Path | str) -> None:
        """
        Generates the virual containers and saves them in a CSV file.

        Parameters
        ----------
        output_file_name : Union[Path, str]
            The path to the CSV file comprising the generated virtual containers

        Returns
        -------
        None

        """
        # generate attributes for num_containers (e.g., 100k) based on the 'prop' values:
        vcons = self.generate_containers()
        # add 'importer' and 'contamination' columns (the latter with values "yes"/"no"):
        self.importer_contamination(vcons)
        # save the containers to a CSV file for simulations:
        vcons.to_csv(output_file_name)


def main(conf: Config) -> None:
    """
    Retrieves the CPT file with 'CALSourceCountryMedium', 'prop' and 'p_yes/no' values
    created by medium_risk_ext.py and proceeds to generate the virtual containers.

    Returns
    -------
    None

    """

    con_object = TheConGen(cpt_top_file=conf.ext_dir / f"{conf.cpt_top}_with_med.csv",
                           num_containers=conf.tot_containers,
                           num_importers=conf.tot_importers)
    if not conf.vcon_dir.exists():
        conf.vcon_dir.mkdir(parents=True, exist_ok=True)
    con_object.generate_sample_containers(conf.vcon_file)


if __name__ == "__main__":
    agp = argparse.ArgumentParser()
    agp.add_argument("--yaml", "-y", required=True, help="path to the YAML input config file")
    ARG = vars(agp.parse_args())
    main(Config(ARG["yaml"]))
